### ISSUE TITLE
.gitignore generation with line ending

### ISSUE THREAD

**Issue by niezbop** [DragonBox/uplift#31]
The .gitignore are generated with CRLF and it causes conflicts in some of our projects where we force line endings to LF.

**Comment by lacostej** [comment]
.gitignore are generated with LF by Uplift since 782a30d9797bbd08dcd14ef5ac8465cee828b002

Not really sure what we mean here by this enhancement.

**Comment by niezbop** [comment]
This issue is not linked with Uplift. It is linked with our git setup. Closing the issue.
