### ISSUE TITLE
update window: consistency issues

### ISSUE THREAD

**Issue by niezbop** [DragonBox/uplift#5]
The update window, still experimental has several issues regarding the integrity and the consistency with the Upfile and the Upfile.lock

- it is possible to update a package in this window even though the updated version would conflict with the requirements of the project. If we want to support this, we should at least warn that this may seriously break a project.

- udpated dependencies in this fashion are not updated in the lockfile.

**Comment by lacostej** [comment]
We should start by making it clear in the window itself that using it may lead to those very weird breakages and that it isn't currently supported.

**Comment by niezbop** [comment]
Agreed! I'll open a pull request for this asap.

**Comment by niezbop** [comment]
Fixed by #7
