### ISSUE TITLE
Git says MIT, docs say All rights reserved

### ISSUE THREAD

**Issue by sjb8100** [DragonBox/uplift#61]
My hope is uplift is under MIT, because I favor it for its taking back control from unity over the unity package manager. However the docs say, "all rights reserved" I wanted to confirm it is under MIT going forward.

https://dragonbox.github.io/uplift_site/index.html#license-copyright-authors

**Comment by lacostej** [comment]
hello @sjb8100, thanks for bringing this to our attention. Uplift is indeed under MIT. We will fix the docs.

**Comment by lacostej** [comment]
@sjb8100 site updated.
